name: Build Android APK 🎮

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Unity Android Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          buildName: BeatRise_TestBuild
          projectPath: .  # Agar subfolder ho toh wahan projectPath mein folder ka naam likhein

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BeatRise-Android-APK
          path: build/Android
          
